name: clean_tdd
description: TDD in Flutter.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.0
  dartz: ^0.10.1
  http: ^0.13.0
  shared_preferences: ^2.0.0
  get_it: ^7.6.0
  data_connection_checker_tv: ^0.3.5-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1

flutter:
  uses-material-design: true
